name = "tabiraices-inventory-api"
main = "src/index.ts"
compatibility_date = "2024-08-15"

[[kv_namespaces]]
binding = "INVENTORY_KV"
id = "0869d4395f1d4f03b2f6e050c32daa87"
preview_id = "0869d4395f1d4f03b2f6e050c32daa87"

[build]
command = "npm run build"
cwd = "."
